version: '3.8'

services:
  talent_dna_be:
    build:
      context: .
      dockerfile: Dockerfile
    image: talent_dna_be
    container_name: talent_dna_be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env


