# Generated by Django 4.1.2 on 2024-06-18 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom5Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('predicted_rank', models.FloatField()),
                ('strength', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('tasks', models.TextField()),
                ('work_styles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Top10Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('predicted_rank', models.FloatField()),
                ('strength', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('top_talent_description', models.TextField()),
                ('bottom_talent_description', models.TextField()),
                ('bottom_5_talents', models.ManyToManyField(to='ml_sys.bottom5talent')),
                ('job_recommendations', models.ManyToManyField(to='ml_sys.jobrecommendation')),
                ('top_10_talents', models.ManyToManyField(to='ml_sys.top10talent')),
            ],
        ),
    ]
